### ISSUE TITLE
Add Issue functionality 

### ISSUE THREAD

**Issue by Brook-A-CS** [CSAllenISD/2023-ISP-Bug-Tracker#14]
ensure that add issue dynamically adds issues by the end of this week

**Comment by RafidAhmed05** [comment]
Here you could use this resource as a way to include the elements needed to next page

https://www.w3schools.com/jsref/tryit.asp?filename=tryjsref_select_options_selindex

**Comment by Aidan-V** [comment]
Using react DOM we are able to accomplish this as the two issue pages are elements defined as useStates.

**Comment by Rafid-A** [comment]
Here you could use this resource as a way to include the elements needed to next page

https://www.w3schools.com/jsref/tryit.asp?filename=tryjsref_select_options_selindex

**Comment by Brook-A-CS** [comment]
Add issue description is now fully functional; the User and priority still need to be added.

**Comment by Brook-A-CS** [comment]
User and priority now work as well
