### ISSUE TITLE
"Current Issue" Box sizing

### ISSUE THREAD

**Issue by Aidan-V** [CSAllenISD/2023-ISP-Bug-Tracker#16]
The current issue use state page minimizes to a smaller box, which must keep to original margins within add issue page and when having multiple issues.

The good sizing
![issue1](https://user-images.githubusercontent.com/89591050/218591712-af8fa708-670e-4bb0-8e17-edb3614bf275.png)

The evil, catastrophic sizing
![issue2](https://user-images.githubusercontent.com/89591050/218591720-04a24941-9178-49f9-bf01-295910e29a99.png)

**Comment by Rafid-A** [comment]
Will Work on that; I'll set both of the boxes to a minimum fixed height, so that doesn't happen. I believe the minimum should be somewhere around 350-360ish px.

**Comment by Brook-A-CS** [comment]
solved using Rafid's solution. After the new changes min is set to 504.54px
