### ISSUE TITLE
Create dynamic user list

### ISSUE THREAD

**Issue by Brook-A-CS** [CSAllenISD/2023-ISP-Bug-Tracker#17]
The assignees are all hard coded, we need to be able to add and remove them from an array.

**Comment by Rafid-A** [comment]
We could create a small database locally with just their names in a JSON file in an array and use their position in the array alongside the selected index in the dropdown to create the dynamic user list

**Comment by Brook-A-CS** [comment]
JSON hasn't been added yet but I was able to add it to an array, similar to how issues are saved currently. We'll focus on JSON implementation when working on a database.
