### ISSUE TITLE
Branch Management

### ISSUE THREAD

**Issue by Rafid-A** [CSAllenISD/2023-ISP-Bug-Tracker#19]
It might be better if we all have separate branches for each of us to work on, like how brook dir dev.brook. Me and Aidan each can do our own dev branch, and then we pick and choose what to merge and what not to merge in the main branch.

**Comment by Aidan-V** [comment]
This is good for tracking everyone's progress but could be too complicated for the release manager to approve all the commits; having fewer branches may prove to be better.

**Comment by Brook-A-CS** [comment]
We can try to make branches whenever one of us is working on a large section of the project. This will ensure that merging branches will be relatively easy as they won't have conflicting code. Overall, feel free to add any branches you think will help.

**Comment by Rafid-A** [comment]
Alright, In that case, we divide it up to Backend Frontend for the time being, in the future, if we need to add any other sections we will make the branches as needed.

**Comment by Aidan-V** [comment]
I agree, separating the two would be good for project and commit management, while also keeping it tidy and organized within the repo.

**Comment by Brook-A-CS** [comment]
We have decided to make branches for each developer and merge to main whenever a major feature is complete.
