### ISSUE TITLE
Possible UI

### ISSUE THREAD

**Issue by Rafid-A** [CSAllenISD/2023-ISP-Bug-Tracker#20]
We could have a separate page with a UI that is similar to the project dashboard that we have access to in CSAllenISD, where it is easy to view each of the individual issues and have the ability to drag them based on their status. This is not necessary just an Idea that could elevate the project.

**Comment by Aidan-V** [comment]
I can definitely see this as a quality of life enhancement that could improve our overall ISP, making it similar to github and elevating to a further level will more than likely prove for success.
