### ISSUE TITLE
Landing Page

### ISSUE THREAD

**Issue by Rafid-A** [CSAllenISD/2023-ISP-Bug-Tracker#21]
I can work on a landing page for the project, so it looks nicer and more presentable. Should I work on it and Is this a good idea or not?

**Comment by Brook-A-CS** [comment]
I think a landing page will look great if you want to work on it. Make sure to leave space for a log in page (if we have time to add a log in system).

**Comment by Rafid-A** [comment]
For the Time Being, I'm not going to consider the login page as something we'll get around to; however, if there is a need, I will page another button on the landing page that will lead to the login page, which we can make easily with another JSX file.

**Comment by Rafid-A** [comment]
With Commit 830676b6f4a271f94bfb429b966d000e193f0a59 I have added a navigation bar to the page alongside other possible page with additional preparation for react-router DOM to connect to our MVP.

**Comment by Rafid-A** [comment]
Alongside the previous commit with this commit 596ba032d69f2a82c0c45ec215f71b50c75678b7 I have added more areas in the landing page to add more descriptions for our product as a little advertisement before they change pages.

**Comment by Rafid-A** [comment]
With Commit a695c76617213c13e27486c04103a1841525549f I have reorganized how the files for the pages will look like in the future, the details are in the message in the commit.

**Comment by Rafid-A** [comment]
I have added most things on the landing page, the only remaining things are pictures towards the bottom for our workflow

**Comment by Rafid-A** [comment]
As of right now, there is nothing more to do for the landing page.
