### ISSUE TITLE
New Assignees Disappear after switching views 

### ISSUE THREAD

**Issue by Brook-A-CS** [CSAllenISD/2023-ISP-Bug-Tracker#23]
Switching to Current issues and back to add issues deletes all added assignees. This does not happen to the list of issues. Most likely it is because the issues array is stored in app.jsx which is always loaded, while assignees is loaded in addIssue.jsx which is loaded and unloaded based on whatever your looking at. While this can be fixed by moving the array position, this presents an optimization opportunity by somehow saving the state of the addIssue page in local storage so that it doesn't have to be loaded everytime the page changes.

**Comment by Aidan-V** [comment]
react DOM could serve as a useful replacement for this, I am currently learning this and hopefully this will prove successful for future endeavors within the ISP.

**Comment by Rafid-A** [comment]
This should be fixed now
