### ISSUE TITLE
Changing Pages, React-Router DOM

### ISSUE THREAD

**Issue by Rafid-A** [CSAllenISD/2023-ISP-Bug-Tracker#24]
Aidan, this week tried to figure out how to use React router DOM properly with a button to change pages. After you have successfully done that, you can implement that into our project by making the button on the landing page go to the Add Issue page and vice versa.

**Comment by Aidan-V** [comment]
react-DOM could be a very useful tool when overhauling our ISP, we can take this into consideration for future notes.

**Comment by Rafid-A** [comment]
In that case, I will start working on learning and using React Router Dom with the landing page soon to link it with our main product.

**Comment by Aidan-V** [comment]
Since I am currently learning this too, I hope we can discuss more about React Router DOM to further our understanding of its back-end operations to display the user's input.

**Comment by Rafid-A** [comment]
I think we should try to get it somewhat working this next week because we have presentation the week after so this working would be massive.

**Comment by Aidan-V** [comment]
This would be a massive milestone for the ISP I agree, this definitely has some potential and opens a lot of possibilities for future implementation. Any team member's thoughts on this would be nice and appreciated when thinking ahead.

**Comment by Rafid-A** [comment]
I have added the necessary things in GitHub for react-router to work, and now I will be closing this issue that it's been resolved.
