### ISSUE TITLE
Scheduling a Meeting

### ISSUE THREAD

**Issue by Rafid-A** [CSAllenISD/2023-ISP-Bug-Tracker#26]
Can we schedule a time to meet on discord to finish this week's work and plan what to do next week? 
I am free after school for the most part.

**Comment by Aidan-V** [comment]
This is a great idea for a team-building activity, and we can also discuss future plans and what we hope to plan accordingly.

**Comment by Brook-A-CS** [comment]
We all agree to plan this on discord, so I'm closing this issue.
