### ISSUE TITLE
Legal Issues

### ISSUE THREAD

**Issue by Aidan-V** [CSAllenISD/2023-ISP-Bug-Tracker#27]
We recently encountered some legal issues regarding resources used, I recently updated the repo to include licensing for our ISP, although I am curious and confused as to how this will affect our ISP, any thoughts?

**Comment by Brook-A-CS** [comment]
What were the resources we had to remove?

**Comment by Rafid-A** [comment]
Uh, long story short, we did not have licenses to our isp stating that all of the work done here was individually our work and that we have copyright over it. We'll discuss it more in our meeting.

**Comment by Rafid-A** [comment]
This issue was addressed in commit 4865ce939343cfb53a7fe223891802bc76646e6f
