### ISSUE TITLE
Future Plans

### ISSUE THREAD

**Issue by Aidan-V** [CSAllenISD/2023-ISP-Bug-Tracker#28]
Every week I want to discuss this so we can discuss future plans or enhancements and what currently stops us from doing so; this is not to have so many ideas that we can only implement some of them. This is only to have a general consensus of all team members' ideas. Feel free to put down your suggestions below.

**Comment by Brook-A-CS** [comment]
This is a great idea, we can easily schedule this in discord. I can do weekends but I understand if you would rather do it on a weekday. Rafid posted a similar issue for a meeting but making it weekly would be nice since we all have different class periods.

**Comment by Rafid-A** [comment]
I say that our plans for the time being should be to fix up some of the broken things we currently have little by little while also developing the calendar system that we talked about in small chunks so we don't overload ourselves; I will continue to work on the landing page until I'm satisfied with it for the time being.

**Comment by Aidan-V** [comment]
Brook, this is true, but this could be useful to tool to journal in, apart from doing such meetings in discord. Thank you for your input however. Rafid, that sounds like a good direction to head in.

**Comment by Rafid-A** [comment]
Right now I believe what we need to focus on is the backed for the most part as we still have some major functionality missing, I will work on React Router Dom as well as some calendar views.

**Comment by Aidan-V** [comment]
This is a great idea, I have recently tried to incorporate react router dom into our ISP, but the initial npm scripts mess with the entirety of the main code utilized to switch me between the use cases that display both the add issue and current issue pages.

**Comment by Rafid-A** [comment]
The thing we need to really work on now is the calender portion, if we can get that working we are basically done with our current ISP plans.

**Comment by Aidan-V** [comment]
This is true, including this into the ISP would better shape upcoming presentations.

**Comment by Rafid-A** [comment]
As of right now we should just finish up our backend and focus on connecting it to the frontend
