### ISSUE TITLE
Add functionality to 'close issue' button 

### ISSUE THREAD

**Issue by Brook-A-CS** [CSAllenISD/2023-ISP-Bug-Tracker#30]
Close issue button is just a place holder for now and doesn't do anything.

**Comment by Aidan-V** [comment]
For this button, should we add a history button that logs all the issues incase it is accidentally closed, or would this enhancement be for a later date?

**Comment by Rafid-A** [comment]
With commit 2edaa25 it adds functionality to the close issue button
