### ISSUE TITLE
QA should use main branch

### ISSUE THREAD

**Issue by Brook-A-CS** [CSAllenISD/2023-ISP-Bug-Tracker#31]
Small, but important, QA, such as typos, can be pushed immediately to main without merging to another branch. If the QA is in an in development feature it can be pushed to the existing branch.

**Comment by Aidan-V** [comment]
Understandable, I take this into account for future commits and encounters.

**Comment by Rafid-A** [comment]
This can only really be done after we merge our branches together to main, so it might be just be better to QA on the feature branches themselves

**Comment by Aidan-V** [comment]
I am completely fine with any other suggestions and will go with this unless stated otherwise.

**Comment by Rafid-A** [comment]
As we are reaching the end of the project we will just QA and merge simultaneously
