### ISSUE TITLE
Uneccessary Comments in Code

### ISSUE THREAD

**Issue by Aidan-V** [CSAllenISD/2023-ISP-Bug-Tracker#32]
I am seeing some unnecessary comments within the ISP's code, try to limit these comments as much as possible and possibly open an issue for future cases.

**Comment by Rafid-A** [comment]
Will do, I have added some redundant code in my branch I will try to fix some of these issues in the next week

**Comment by Aidan-V** [comment]
Great news, glad this issue has been heard, valued, and interacted with by the team.

**Comment by Rafid-A** [comment]
Update: Most of the redundant code and unnecessary lines have been cleared out from my branch.

**Comment by Aidan-V** [comment]
I also removed some unnecessary css lines that did not impact the landing page.

**Comment by Rafid-A** [comment]
Most if not all of this has been completed
