### ISSUE TITLE
Consider Back end technologies

### ISSUE THREAD

**Issue by Brook-A-CS** [CSAllenISD/2023-ISP-Bug-Tracker#34]
We have several options for developing our back end and database. One way we can do it is through our codermerlin website. This allows us to have a static URL. We can also research other free online alternatives.

**Comment by MasonG31** [comment]
I think that using the coder merlin website is going to be the most comfortable, but using other applications would increase the quality of the product. We need to decide where we draw the line between comfort and quality.

**Comment by Rafid-A** [comment]
This would probably work the best as this is the easiest to access server technology for us, but we can still consider some other websites like MongoDB

**Comment by Brook-A-CS** [comment]
I chose to use a express due to keeping everything in javascript as well as it being a popular backend option which will help with finding libraries and make it easier to learn.
