### ISSUE TITLE
Migrate locally stored arrays into server.

### ISSUE THREAD

**Issue by Brook-A-CS** [CSAllenISD/2023-ISP-Bug-Tracker#36]
Currently both the issues array as well as the assignee list array are stored locally but not saved meaning any time the app is refreshed it loses all of the data in these arrays. Having a server will allow us to keep track of everything.

**Comment by Rafid-A** [comment]
Our best best is probably the vapor servers in Codermerlin

**Comment by Aidan-V** [comment]
This is a great idea, using the resources we have available it will keep up to date as long as the school allows.

**Comment by Brook-A-CS** [comment]
https://github.com/CSAllenISD/2023-ISP-Bug-Tracker/issues/46
