### ISSUE TITLE
Pages not working

### ISSUE THREAD

**Issue by Brook-A-CS** [CSAllenISD/2023-ISP-Bug-Tracker#41]
After merging to main, the CSS, specifically margins, are not applying properly to the add issue page. This is most likely a file pathing issue and can be resolved relatively quickly, however there's a bigger issue with the issues display page. Currently it shows nothing, which could possibly be a result of the new routing that was implemented contradicting with the issue page's ability to receive data from the 'addissue' page since this version of the code is not fully connected to the server yet. Overall we need to quickly fix these small, but largely consequential bugs

**Comment by Rafid-A** [comment]
This is fixed with the recent merges I made to the main branch
