### ISSUE TITLE
Decide on Technologies

### ISSUE THREAD

**Issue by RafidAhmed05** [CSAllenISD/2023-ISP-Bug-Tracker#5]
Before we start, we need to decide on what type of program we are creating and the technologies we are going to use to create it.
The technology I was looking to use is ReactJS to create the application and work on it.

**Comment by Aidan-V** [comment]
I completely agree, ReactJS seems like a great way to develop the app in a web based platform.

**Comment by Brook-A-CS** [comment]
React sounds good for front end. For backend we should use nodeJS which will be good due to its flexibility from libraries and its common use in the professional world will help us build our resumes,
