### ISSUE TITLE
Time Allocation/Communication

### ISSUE THREAD

**Issue by RafidAhmed05** [CSAllenISD/2023-ISP-Bug-Tracker#6]
Since we are all in separate classes, communication is going to be a bit of a problem alongside that we also need to manage our time for the project, a big part of that would be when we all can work together on a part of the project so we need to create a calendar/timeline of when we are going to do something and try to follow it as closely as possible for the best results.

**Comment by Aidan-V** [comment]
Using a third part app for messaging will best help planning time constraints, team planning, and general team communication.
